// Dumps the sim's own Laser hull to an OBJ the renderer can load.
//
// The native client ABI exports no hull geometry on purpose: SimBoatIdentity carries a class_id and
// tells the engine to "resolve your mesh and rig by this", so the hull is the renderer's asset. The
// sim still owns the authoritative shape in C# (RoundBilgeLaserHullMesh), and this tool is the
// one-way bridge between those two facts - run it when the sim's hull changes, commit the result.
//
//     dotnet run --project tools/hull-export -- models/laser-hull.obj
//
// Emitted in the RENDERER's frame, not the sim's. The sim is right-handed Z-up (+x bow, +y port,
// +z up, waterline z=0); this renderer is left-handed Y-up, and the map between them swaps y and z.
// That swap has determinant -1, so it is a handedness change and not a rotation: the boat's world
// matrix carries only the mapped quaternion (a proper rotation), which expects its mesh to already
// be in the renderer's frame. Baking it here is therefore not an extra correction, it is the one
// place the frame change can live without a det -1 factor in a world matrix flipping every face.
//
// Triangle winding is reversed to match. The sim authors CCW-outward in its own frame; swapping two
// axes mirrors the geometry, so keeping the original order would leave every normal pointing INTO
// the hull, and the loader derives its normals from winding.
using System;
using System.Globalization;
using System.IO;
using System.Text;
using Sim.Models.Hydro;

var outPath = args.Length > 0 ? args[0] : "models/laser-hull.obj";

var mesh = RoundBilgeLaserHullMesh.BuildVisual();

var sb = new StringBuilder();
sb.AppendLine("# Laser hull - GENERATED by tools/hull-export, do not edit by hand.");
sb.AppendLine("# Source: Sim.Models.Hydro.RoundBilgeLaserHullMesh.BuildVisual()");
sb.AppendLine("# Frame: RENDERER left-handed Y-up (+x bow, +y up, +z starboard); waterline y=0. Units: metres.");
sb.AppendLine(CultureInfo.InvariantCulture, $"# {mesh.Vertices_B.Count} vertices, {mesh.TriangleCount} triangles.");
sb.AppendLine("o laser_hull");

foreach (var v in mesh.Vertices_B)
{
    sb.AppendLine(CultureInfo.InvariantCulture, $"v {v.X:0.######} {v.Z:0.######} {v.Y:0.######}");
}

// No vn lines: the renderer's ObjLoader accumulates face normals into smooth per-vertex normals when
// a file carries none, which is what a round-bilge hull wants anyway.
for (var i = 0; i < mesh.TriangleIndices.Count; i += 3)
{
    var a = mesh.TriangleIndices[i] + 1;      // OBJ indices are 1-based
    var b = mesh.TriangleIndices[i + 1] + 1;
    var c = mesh.TriangleIndices[i + 2] + 1;
    sb.AppendLine(CultureInfo.InvariantCulture, $"f {a} {c} {b}");   // reversed: see the note above
}

var full = Path.GetFullPath(outPath);
Directory.CreateDirectory(Path.GetDirectoryName(full)!);
File.WriteAllText(full, sb.ToString());

Console.WriteLine($"wrote {full}: {mesh.Vertices_B.Count} verts, {mesh.TriangleCount} tris");
